repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt --all'
        language: system
        files: \.rs$

      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c 'cargo clippy --workspace --all-targets -- -D warnings'
        language: system
        files: \.rs$

      - id: cargo-test
        name: cargo test
        entry: bash -c 'cargo test --workspace --lib'
        language: system
        files: \.rs$
